_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

max_steps: 100
log_every_n_steps: 10
val_check_interval: 10
check_val_every_n_epoch: null

accelerator: gpu
devices: 1

precision: bf16-mixed
gradient_clip_val: 1.0

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: True
